Traceback (most recent call last):
  File "/Users/rvdbie/Documents/03_Python/PythonScripts/errorExample2.py", line 3, in <module>
    raise Exception('This is the error msg!')
Exception: This is the error msg!
